"""Reduced-order model of `comb_resonator` — generated by soidlc.

Modal superposition of the lowest 3 FEM modes; comb transducers
enter via modal participation factors. m_eff=5.728e-09 kg, k_eff=2.164e+02 N/m, Q≈617.
"""

import math

F_MODES = [30932.262, 753963.841, 754536.187]
ZETA = [0.00081066, 0.0001, 0.0001]
PORTS = {'DRIVE': {'dcdx': 5.3125126876800004e-09, 'C0': 2.0187548213183998e-13, 'u': [-13212.69254130298, 480.64117134287346, -572.8186760757736]}, 'SENSE': {'dcdx': 5.3125126876800004e-09, 'C0': 2.0187548213183998e-13, 'u': [13212.69254130314, -480.608485177196, 572.730189630098]}}
DRIVE_PORT = 'DRIVE'
SENSE_PORT = 'SENSE'
V_DC = 30.0
M_EFF = 5.728189037535564e-09
K_EFF = 216.37169260498007
Q1 = 616.7824200121357


def force(port, V):
    """Electrostatic comb force, N (always attractive along +u)."""
    return 0.5 * PORTS[port]["dcdx"] * V * V


def _deriv(state, Vd):
    F = force(DRIVE_PORT, Vd)
    ud = PORTS[DRIVE_PORT]["u"]
    out = []
    for i, f in enumerate(F_MODES):
        w = 2.0 * math.pi * f
        q, v = state[2 * i], state[2 * i + 1]
        out.append(v)
        out.append(-w * w * q - 2.0 * ZETA[i] * w * v + ud[i] * F)
    return out


def displacement(port, state):
    """Physical displacement at a port's rotor, metres."""
    u = PORTS[port]["u"]
    return sum(u[i] * state[2 * i] for i in range(len(F_MODES)))


def velocity(port, state):
    u = PORTS[port]["u"]
    return sum(u[i] * state[2 * i + 1] for i in range(len(F_MODES)))


def sense_current(state, v_bias=V_DC):
    """Motional current at the sense port, A."""
    return v_bias * PORTS[SENSE_PORT]["dcdx"] * velocity(SENSE_PORT, state)


def simulate(v_drive, t_end, dt=None, state=None):
    """RK4 transient.  ``v_drive(t)`` -> volts.  Returns (t, x_sense, i_sense)."""
    if dt is None:
        dt = 1.0 / (25.0 * max(F_MODES))
    if state is None:
        state = [0.0] * (2 * len(F_MODES))
    ts, xs, cur = [], [], []
    t = 0.0
    while t < t_end:
        v = v_drive(t)
        k1 = _deriv(state, v)
        k2 = _deriv([s + 0.5 * dt * k for s, k in zip(state, k1)],
                    v_drive(t + 0.5 * dt))
        k3 = _deriv([s + 0.5 * dt * k for s, k in zip(state, k2)],
                    v_drive(t + 0.5 * dt))
        k4 = _deriv([s + dt * k for s, k in zip(state, k3)],
                    v_drive(t + dt))
        state = [s + dt / 6.0 * (a + 2 * b + 2 * c + d)
                 for s, a, b, c, d in zip(state, k1, k2, k3, k4)]
        t += dt
        ts.append(t)
        xs.append(displacement(SENSE_PORT, state))
        cur.append(sense_current(state))
    return ts, xs, cur


def freq_response(f, drive=None, sense=None):
    """Complex mechanical transfer x_sense/F_drive (m/N) at frequency f."""
    drive = drive or DRIVE_PORT
    sense = sense or SENSE_PORT
    ud, us = PORTS[drive]["u"], PORTS[sense]["u"]
    w = 2.0 * math.pi * f
    H = 0j
    for i, fi in enumerate(F_MODES):
        wi = 2.0 * math.pi * fi
        H += ud[i] * us[i] / (wi * wi - w * w + 2j * ZETA[i] * wi * w)
    return H


def estimate_resonance():
    """Ring-down test: static comb deflection released at t=0; the dominant
    zero-crossing rate of the drive-point displacement gives f1."""
    F0 = force(DRIVE_PORT, V_DC)
    ud = PORTS[DRIVE_PORT]["u"]
    state = []
    for i, f in enumerate(F_MODES):
        w = 2.0 * math.pi * f
        state += [ud[i] * F0 / (w * w), 0.0]
    t_end = 30.0 / F_MODES[0]
    dt = 1.0 / (25.0 * max(F_MODES))
    t, crossings, prev, t_first, t_last = 0.0, 0, None, None, None
    while t < t_end:
        k1 = _deriv(state, 0.0)
        k2 = _deriv([s + 0.5 * dt * k for s, k in zip(state, k1)], 0.0)
        k3 = _deriv([s + 0.5 * dt * k for s, k in zip(state, k2)], 0.0)
        k4 = _deriv([s + dt * k for s, k in zip(state, k3)], 0.0)
        state = [s + dt / 6.0 * (a + 2 * b + 2 * c + d)
                 for s, a, b, c, d in zip(state, k1, k2, k3, k4)]
        t += dt
        x = displacement(DRIVE_PORT, state)
        if prev is not None and prev < 0.0 <= x:
            crossings += 1
            t_last = t
            if t_first is None:
                t_first = t
        prev = x
    if crossings < 2:
        return 0.0
    return (crossings - 1) / (t_last - t_first)


if __name__ == "__main__":
    f_est = estimate_resonance()
    print("ring-down resonance : %.1f Hz  (modal f1 = %.1f Hz)"
          % (f_est, F_MODES[0]))
    H = abs(freq_response(F_MODES[0]))
    print("peak |x_sense/F|    : %.3e m/N  (Q*static)" % H)
    print("static sense defl.  : %.3e m at V_dc" % (
        abs(freq_response(1.0)) * force(DRIVE_PORT, V_DC)))
