"""Reduced-order model of `comb_resonator` — generated by soidlc.

Modal superposition of the lowest 3 FEM modes; comb transducers
enter via modal participation factors. m_eff=5.698e-09 kg, k_eff=1.009e+02 N/m, Q≈449.
"""

import math

F_MODES = [21180.225, 452875.555, 454671.506]
ZETA = [0.00111271, 0.0001, 0.0001]
PORTS = {'DRIVE': {'dcdx': 3.76302982044e-09, 'C0': 1.4299513317671997e-13, 'u': [-13247.804713828193, -386.01924207575047, 949.303214041144]}, 'SENSE': {'dcdx': 5.3125126876800004e-09, 'C0': 2.0187548213183998e-13, 'u': [13247.791553579622, 386.17141227563076, -948.1866241742086]}}
DRIVE_PORT = 'DRIVE'
SENSE_PORT = 'SENSE'
V_DC = 30.0
M_EFF = 5.697865126779399e-09
K_EFF = 100.90972475731819
Q1 = 449.35211135665475
B_TOTAL = 1.6874690129530253e-06     # total gas damping, N*s/m
X_DRIVE = 7.540565882433071e-06     # resonant drive amplitude at V_DC, m
ARW_RADS = 1.0339002543394398e-05     # analytic ARW @300K, rad/sqrt(s)


def force(port, V):
    """Electrostatic comb force, N (always attractive along +u)."""
    return 0.5 * PORTS[port]["dcdx"] * V * V


def _deriv(state, Vd):
    F = force(DRIVE_PORT, Vd)
    ud = PORTS[DRIVE_PORT]["u"]
    out = []
    for i, f in enumerate(F_MODES):
        w = 2.0 * math.pi * f
        q, v = state[2 * i], state[2 * i + 1]
        out.append(v)
        out.append(-w * w * q - 2.0 * ZETA[i] * w * v + ud[i] * F)
    return out


def displacement(port, state):
    """Physical displacement at a port's rotor, metres."""
    u = PORTS[port]["u"]
    return sum(u[i] * state[2 * i] for i in range(len(F_MODES)))


def velocity(port, state):
    u = PORTS[port]["u"]
    return sum(u[i] * state[2 * i + 1] for i in range(len(F_MODES)))


def sense_current(state, v_bias=V_DC):
    """Motional current at the sense port, A."""
    return v_bias * PORTS[SENSE_PORT]["dcdx"] * velocity(SENSE_PORT, state)


def simulate(v_drive, t_end, dt=None, state=None):
    """RK4 transient.  ``v_drive(t)`` -> volts.  Returns (t, x_sense, i_sense)."""
    if dt is None:
        dt = 1.0 / (25.0 * max(F_MODES))
    if state is None:
        state = [0.0] * (2 * len(F_MODES))
    ts, xs, cur = [], [], []
    t = 0.0
    while t < t_end:
        v = v_drive(t)
        k1 = _deriv(state, v)
        k2 = _deriv([s + 0.5 * dt * k for s, k in zip(state, k1)],
                    v_drive(t + 0.5 * dt))
        k3 = _deriv([s + 0.5 * dt * k for s, k in zip(state, k2)],
                    v_drive(t + 0.5 * dt))
        k4 = _deriv([s + dt * k for s, k in zip(state, k3)],
                    v_drive(t + dt))
        state = [s + dt / 6.0 * (a + 2 * b + 2 * c + d)
                 for s, a, b, c, d in zip(state, k1, k2, k3, k4)]
        t += dt
        ts.append(t)
        xs.append(displacement(SENSE_PORT, state))
        cur.append(sense_current(state))
    return ts, xs, cur


def freq_response(f, drive=None, sense=None):
    """Complex mechanical transfer x_sense/F_drive (m/N) at frequency f."""
    drive = drive or DRIVE_PORT
    sense = sense or SENSE_PORT
    ud, us = PORTS[drive]["u"], PORTS[sense]["u"]
    w = 2.0 * math.pi * f
    H = 0j
    for i, fi in enumerate(F_MODES):
        wi = 2.0 * math.pi * fi
        H += ud[i] * us[i] / (wi * wi - w * w + 2j * ZETA[i] * wi * w)
    return H


def estimate_resonance():
    """Ring-down test: static comb deflection released at t=0; the dominant
    zero-crossing rate of the drive-point displacement gives f1."""
    F0 = force(DRIVE_PORT, V_DC)
    ud = PORTS[DRIVE_PORT]["u"]
    state = []
    for i, f in enumerate(F_MODES):
        w = 2.0 * math.pi * f
        state += [ud[i] * F0 / (w * w), 0.0]
    t_end = 30.0 / F_MODES[0]
    dt = 1.0 / (25.0 * max(F_MODES))
    t, crossings, prev, t_first, t_last = 0.0, 0, None, None, None
    while t < t_end:
        k1 = _deriv(state, 0.0)
        k2 = _deriv([s + 0.5 * dt * k for s, k in zip(state, k1)], 0.0)
        k3 = _deriv([s + 0.5 * dt * k for s, k in zip(state, k2)], 0.0)
        k4 = _deriv([s + dt * k for s, k in zip(state, k3)], 0.0)
        state = [s + dt / 6.0 * (a + 2 * b + 2 * c + d)
                 for s, a, b, c, d in zip(state, k1, k2, k3, k4)]
        t += dt
        x = displacement(DRIVE_PORT, state)
        if prev is not None and prev < 0.0 <= x:
            crossings += 1
            t_last = t
            if t_first is None:
                t_first = t
        prev = x
    if crossings < 2:
        return 0.0
    return (crossings - 1) / (t_last - t_first)


KB = 1.380649e-23
T_REF = 300.0


def equivalent_rate_psd(T=T_REF):
    """One-sided PSD of the thermal-equivalent input rate, (rad/s)^2/Hz.

    Fluctuation-dissipation: force PSD 4*kB*T*B_TOTAL referred through the
    Coriolis scale factor 2*M_EFF*w_drive*X_DRIVE.
    """
    sf = 2.0 * M_EFF * (2.0 * math.pi * F_MODES[0]) * X_DRIVE
    return 4.0 * KB * T * B_TOTAL / (sf * sf)


def arw(T=T_REF):
    """Angle random walk, rad/sqrt(s) (IEEE-952: sigma(tau)=ARW/sqrt(tau))."""
    return math.sqrt(equivalent_rate_psd(T) / 2.0)


def allan_deviation(y, dt, ms=None):
    """Overlapping Allan deviation of a rate record. -> [(tau, sigma)]."""
    n = len(y)
    if ms is None:
        ms, m = [], 1
        while m <= n // 10:
            ms.append(m)
            m *= 2
    th = [0.0] * (n + 1)            # cumulative angle
    for i, v in enumerate(y):
        th[i + 1] = th[i] + v * dt
    out = []
    for m in ms:
        tau = m * dt
        cnt = n - 2 * m + 1
        s = 0.0
        for k in range(cnt):
            d = th[k + 2 * m] - 2.0 * th[k + m] + th[k]
            s += d * d
        out.append((tau, math.sqrt(s / (2.0 * tau * tau * cnt))))
    return out


def arw_experiment(T=T_REF, n=200000, dt=1e-3, seed=2):
    """Virtual rate-table run at Omega = 0: the gyro output is pure
    thermal-equivalent rate noise; its Allan deviation follows
    sigma(tau) = ARW/sqrt(tau).  Returns ([(tau, sigma)], arw_estimate)."""
    import random
    rng = random.Random(seed)
    sig = math.sqrt(equivalent_rate_psd(T) / (2.0 * dt))
    y = [rng.gauss(0.0, sig) for _ in range(n)]
    pts = allan_deviation(y, dt)
    est = sum(s * math.sqrt(t) for t, s in pts[:4]) / 4.0
    return pts, est


def thermal_x_rms(T=T_REF):
    """Equipartition: expected RMS thermal displacement, sqrt(kB*T/k)."""
    return math.sqrt(KB * T / K_EFF)


def simulate_thermal(t_end, T=T_REF, dt=None, seed=1, n_modes=None):
    """Langevin integration (semi-implicit Euler) under thermal force only.
    The modal damping and the thermal forcing are tied by the
    fluctuation-dissipation theorem, so equipartition holds:
    <x^2> -> kB*T/K_EFF.  Returns (dt, x_samples) at the drive point."""
    import random
    nm = n_modes or len(F_MODES)
    if dt is None:
        dt = 1.0 / (40.0 * max(F_MODES[:nm]))
    rng = random.Random(seed)
    sig_f = math.sqrt(2.0 * KB * T * B_TOTAL / dt)
    ud = PORTS[DRIVE_PORT]["u"]
    state = [0.0] * (2 * nm)
    xs = []
    for _ in range(int(t_end / dt)):
        fth = rng.gauss(0.0, sig_f)
        for i in range(nm):
            w = 2.0 * math.pi * F_MODES[i]
            v = state[2 * i + 1] + (
                -w * w * state[2 * i]
                - 2.0 * ZETA[i] * w * state[2 * i + 1]
                + ud[i] * fth) * dt
            state[2 * i + 1] = v
            state[2 * i] += v * dt
        xs.append(sum(ud[i] * state[2 * i] for i in range(nm)))
    return dt, xs


if __name__ == "__main__":
    f_est = estimate_resonance()
    print("ring-down resonance : %.1f Hz  (modal f1 = %.1f Hz)"
          % (f_est, F_MODES[0]))
    H = abs(freq_response(F_MODES[0]))
    print("peak |x_sense/F|    : %.3e m/N  (Q*static)" % H)
    print("static sense defl.  : %.3e m at V_dc" % (
        abs(freq_response(1.0)) * force(DRIVE_PORT, V_DC)))
    print("ARW analytic        : %.4f deg/sqrt(h)"
          % (arw() * (180.0 / math.pi) * 60.0))
    _pts, _est = arw_experiment(n=100000)
    print("ARW from Allan exp. : %.4f deg/sqrt(h)"
          % (_est * (180.0 / math.pi) * 60.0))
    _dt, _xs = simulate_thermal(0.25, n_modes=1, seed=3)
    _rms = math.sqrt(sum(x * x for x in _xs) / len(_xs))
    print("thermal x_rms       : %.2e m (equipartition: %.2e m)"
          % (_rms, thermal_x_rms()))
